before:
  hooks:
  - go mod download
builds:
- id: amtui
  main: .
  binary: amtui
  env:
  - CGO_ENABLED=0
  ldflags: -s -w -X github.com/pehlicd/amtui/pkg.versionString={{ .Tag }} -X github.com/pehlicd/amtui/pkg.buildDate={{ .Date }} -X github.com/pehlicd/amtui/pkg.buildCommit={{ .Commit }}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64

archives:
- builds:
  - amtui
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE